Rails/AGB/config/routes.rb
AGB::Application.routes.draw do
  
  root to: 'application#index', via: :get

  get "session" => "session#show"
  post "session" => "session#create"
  delete "session" => "session#destroy"

  resources :client_views, only: [:show]
  constraints id: '[a-zA-Z0-9\_\-]+' do
    get ":id/edit" => "users#edit", as: 'edit_user'
    resources :users, except: [ :new, :index ], constraints: {user_id: '[a-zA-Z0-9\_\-]+'} do
      resources :projects, except: [ :index ], constraints: {project_id: '.[a-zA-Z0-9\_\-]+'} do
        get "worldmaker" => "worldmaker#index"
        get "worldmaker/world" => "worldmaker#world"
        put "worldmaker/world" => "worldmaker#update"
        resources :resources
        resources :project_comments
      end
    end
  end

end

Rails/AGB/app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :name, :nb_stars, :privacy, :user, :user_id, :project_comments
  validates :name, presence: true, length: { in: 3..20 }
  validates :description, length: { maximum: 1000 }
  validates :privacy, presence: true, inclusion: ["public", "private"]
  validates :nb_stars, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }

  # checks the uniqueness by user
  validates_each :name do |record, attr, value|
  	# shouldnt be there 
  	unless record.user.nil?
	  	record.errors.add(attr, "Project already exists") unless record.user.projects.reject { |proj| proj.name != value }.empty?
	end
  end

  belongs_to :user
  has_many :project_comments

  after_create :create_project_tree

  def create_project_tree
    begin
      project_path = "#{Rails.root}/#{AGB_CONFIG['users_dir']}/#{self.user.name}/#{self.name}"
      Dir.mkdir(project_path, 0755)
      Dir.mkdir("#{project_path}/Resources", 0755)
      Dir.mkdir("#{project_path}/kFiles", 0755)
      ResourcesController.create_world_file("#{project_path}/kFiles/world.json")
    rescue
      self.destroy
      self.errors[:internal] = "- Internal server error: Please contact an administrator."
      puts "Cannot create the project tree for the project #{self.name} [owner: #{self.user.name}]"
    end
  end

  after_destroy :destroy_project_tree

  def destroy_project_tree
    project_path = "#{Rails.root}/#{AGB_CONFIG['users_dir']}/#{self.user.name}/#{self.name}"
    
    begin
      FileUtils.remove_entry_secure(project_path);
    rescue
      puts "Cannot remove the project directory #{project_path}"
      # Do something... send mail to administrator?
    end
  end

  def to_param
    name
  end
end

Rails/AGB/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :load_project, except: [:new, :create ]

  def load_project
    user = User.find_by_name(params[:user_id]) || not_found
    @project = user.projects.find_by_name(params[:id]) || not_found
  end

  # GET /username/projectname
  def show
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /username/new
  def new
    @user = User.find_by_name(params[:user_id]) || not_found
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /username/projectname/edit
  def edit
    @user = @project.user
  end

  # POST /projects
  def create
    @user = User.find_by_name(params[:user_id])
    @project = @user.projects.new params[:project]
    @project.nb_stars = 0

    if (@project.save && !@project.errors.any?)
      render json: {}.to_json, status: 200
    else
      render json: { errors: @project.errors }.to_json, status: 500
    end
  end

  # PUT /username/projectname/
  def update
    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to [@project.user, @project], notice: 'Project was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /username/projectname/
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(user_url(@project.user), notice: 'Project was successfully destroyed.') }
    end
  end
end

Rails/AGB/app/helpers/projects_helper.rb
module ProjectsHelper
end

Rails/AGB/app/views/projects/_form.html.erb
<%= form_for([@user, @project]) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :privacy %><br />
    <%= f.text_field :privacy %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/AGB/app/views/projects/_index.html.erb
<h3>Listing projects</h3>
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Privacy</th>
    <th>Nb stars</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user.projects.each do |project| %>
  <tr id="<%= project.name %>">
    <td><%= project.name %></td>
    <td><%= project.description %></td>
    <td><%= project.privacy %></td>
    <td><%= project.nb_stars %></td>
    <td><%= link_to 'Show', user_project_path(@user, project) %> | </td>
    <td><%= link_to 'World Maker', user_project_worldmaker_path(@user, project) %> | </td>
    <td><%= link_to 'Edit', edit_user_project_path(@user, project) %> | </td>
    <% if (Rails.env != 'test') %>
      <td><%= link_to 'Destroy', user_project_path(@user, project), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% else %>
      <td><%= link_to 'Destroy', user_project_path(@user, project), method: :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_user_project_path(@user) %>

Rails/AGB/app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', [@project.user, @project] %>
<%= link_to 'Back', user_path(@project.user) %>

Rails/AGB/app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', user_path(@user) %>

Rails/AGB/app/views/projects/show.html.erb
<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Description:</b>
  <%= @project.description %>
</p>

<p>
  <b>Privacy:</b>
  <%= @project.privacy %>
</p>

<p>
  <b>Nb stars:</b>
  <%= @project.nb_stars %>
</p>

<p>
  <b>User:</b>
  <%= @project.user.name %>
</p>

<%= link_to 'World Maker', user_project_worldmaker_path(@project.user, @project) %> | 
<%= link_to 'Edit', edit_user_project_path(@project.user, @project) %> | 
<%= link_to 'Back', user_path(@project.user) %>