Rails/AGB/config/routes.rb
AGB::Application.routes.draw do
  
  root to: 'application#index', via: :get

  get "session" => "session#show"
  post "session" => "session#create"
  delete "session" => "session#destroy"

  resources :client_views, only: [:show]
  constraints id: '[a-zA-Z0-9\_\-]+' do
    get ":id/edit" => "users#edit", as: 'edit_user'
    resources :users, except: [ :new, :index ], constraints: {user_id: '[a-zA-Z0-9\_\-]+'} do
      resources :projects, except: [ :index ], constraints: {project_id: '.[a-zA-Z0-9\_\-]+'} do
        get "worldmaker" => "worldmaker#index"
        get "worldmaker/world" => "worldmaker#world"
        put "worldmaker/world" => "worldmaker#update"
        resources :resources
        resources :project_comments
      end
    end
  end

end

Rails/AGB/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation, :projects, :project_comments
  validates :name, presence: true, uniqueness: true, length: { in: 3..20 }
  validates :email, presence: true, uniqueness: true, email: true
  validates :password, presence: true, length:  { in: 6..20 }

  has_secure_password

  has_many :projects
  has_many :project_comments

  after_create :create_user_dir

  def create_user_dir
    begin
      Dir.mkdir("#{Rails.root}/#{AGB_CONFIG['users_dir']}/#{self.name}", 0755)
    rescue
      self.destroy
      self.errors[:internal] = "Internal server error: Please contact an administrator."
      puts "Cannot create the user directory #{Rails.root}/#{AGB_CONFIG['users_dir']}/#{self.name}"
    end
  end

  after_destroy :destroy_user_dir
  
  def destroy_user_dir
    begin
      FileUtils.remove_entry_secure("#{AGB_CONFIG['users_dir']}/#{self.name}");
    rescue
      puts "Cannot remove the user directory #{AGB_CONFIG['users_dir']}/#{self.name}"
      # Do something... send mail to administrator?
    end
  end

  def to_param
  	name
  end
end

Rails/AGB/app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  before_filter :load_user, except: [ :create ]

  def load_user
    @user = User.find_by_name(params[:id]) || not_found
  end

  # GET /username
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # POST /
  def create
    @user = User.new(params[:user])

    if (@user.save == false)
      render json: { status: 'failure', errors: @user.errors }.to_json, status: 500
    else
      render json: {}.to_json, status: 200
    end
  end

  # PUT /username
  def update
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /username
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: 'User was successfully deleted'}
    end
  end
end

Rails/AGB/app/helpers/users_helper.rb
module UsersHelper
end

Rails/AGB/app/views/users/_edit.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/AGB/app/views/users/_new.html.erb
<%= form_for User.new, remote: true do |f| %>
  <p><center id="message">Fill your informations.</center></p>
  <div class="field">
    <%= f.text_field :name, size: UsersController.input_size, placeholder: "name" %>
    <center class="field-error"></center>
  </div>
  <div class="field">
    <%= f.password_field :password, size: UsersController.input_size, placeholder: "password" %>
    <center class="field-error"></center>
  </div>
  <div class="field" >
    <%= f.password_field :password_confirmation, size: UsersController.input_size, placeholder: "confirmation" %>
    <center class="field-error"></center>
  </div>
  <div class="field">
    <%= f.text_field :email, placeholder: "email" %>
    <center class="field-error"></center>
  </div>
  <div class="actions pull-right">
    <%= f.submit "Sign Up", class: "btn btn-inverse" %>
  </div>
<% end %>

Rails/AGB/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Password</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.password %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

Rails/AGB/app/views/users/show.html.erb
<div id="user-profile">
	<p>
	  <h3>User profile</h3>
	  <b>Name:</b>
	  <%= @user.name %>
	</p>

	<p>
	  <b>Email:</b>
	  <%= @user.email %>
	</p>

	<%= link_to 'Destroy User', user_path(@user), method: :delete, confirm: "Are you sure?" %>
</div>
<div id="user-projects">
	<p>
		<%= render 'projects/index' %>
	</p>
</div>