Rails/AGB/config/routes.rb
AGB::Application.routes.draw do
  
  root to: 'application#index', via: :get

  get "session" => "session#show"
  post "session" => "session#create"
  delete "session" => "session#destroy"

  resources :client_views, only: [:show]
  constraints id: '[a-zA-Z0-9\_\-]+' do
    get ":id/edit" => "users#edit", as: 'edit_user'
    resources :users, except: [ :new, :index ], constraints: {user_id: '[a-zA-Z0-9\_\-]+'} do
      resources :projects, except: [ :index ], constraints: {project_id: '.[a-zA-Z0-9\_\-]+'} do
        get "worldmaker" => "worldmaker#index"
        get "worldmaker/world" => "worldmaker#world"
        put "worldmaker/world" => "worldmaker#update"
        resources :resources
        resources :project_comments
      end
    end
  end

end

Rails/AGB/app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.number_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :file %><br />
    <%= f.text_field :file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/AGB/app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

Rails/AGB/app/views/resources/index.html.erb
<h1>Listing resources</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Project</th>
    <th>File</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @resources.each do |resource| %>
  <tr>
    <td><%= resource.name %></td>
    <td><%= resource.project_id %></td>
    <td><%= resource.file %></td>
    <td><%= link_to 'Show', resource %></td>
    <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
    <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resource', new_resource_path %>

Rails/AGB/app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

Rails/AGB/app/views/resources/show.html.erb
<p>
  <b>Name:</b>
  <%= @resource.name %>
</p>

<p>
  <b>Project:</b>
  <%= @resource.project_id %>
</p>

<p>
  <b>File:</b>
  <%= @resource.file %>
</p>


<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>