Rails/AGB/config/routes.rb
AGB::Application.routes.draw do
  
  root to: 'application#index', via: :get

  get "session" => "session#show"
  post "session" => "session#create"
  delete "session" => "session#destroy"

  resources :client_views, only: [:show]
  constraints id: '[a-zA-Z0-9\_\-]+' do
    get ":id/edit" => "users#edit", as: 'edit_user'
    resources :users, except: [ :new, :index ], constraints: {user_id: '[a-zA-Z0-9\_\-]+'} do
      resources :projects, except: [ :index ], constraints: {project_id: '.[a-zA-Z0-9\_\-]+'} do
        get "worldmaker" => "worldmaker#index"
        get "worldmaker/world" => "worldmaker#world"
        put "worldmaker/world" => "worldmaker#update"
        resources :resources
        resources :project_comments
      end
    end
  end

end

Rails/AGB/app/models/project_comment.rb
class ProjectComment < ActiveRecord::Base
  attr_accessible :content, :project, :project_id, :title, :user, :user_id
  validates :content, length: { in: 1..200 }
  validates :title, length: { in: 1..200 }

  belongs_to :project
  belongs_to :user
end

Rails/AGB/app/controllers/project_comments_controller.rb
class ProjectCommentsController < ApplicationController
  # GET /project_comments
  # GET /project_comments.json
  def index
    @project_comments = ProjectComment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @project_comments }
    end
  end

  # GET /project_comments/1
  # GET /project_comments/1.json
  def show
    @project_comment = ProjectComment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project_comment }
    end
  end

  # GET /project_comments/new
  # GET /project_comments/new.json
  def new
    @project_comment = ProjectComment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project_comment }
    end
  end

  # GET /project_comments/1/edit
  def edit
    @project_comment = ProjectComment.find(params[:id])
  end

  # POST /project_comments
  # POST /project_comments.json
  def create
    @project_comment = ProjectComment.new(params[:project_comment])

    respond_to do |format|
      if @project_comment.save
        format.html { redirect_to @project_comment, notice: 'Project comment was successfully created.' }
        format.json { render json: @project_comment, status: :created, location: @project_comment }
      else
        format.html { render action: "new" }
        format.json { render json: @project_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /project_comments/1
  # PUT /project_comments/1.json
  def update
    @project_comment = ProjectComment.find(params[:id])

    respond_to do |format|
      if @project_comment.update_attributes(params[:project_comment])
        format.html { redirect_to @project_comment, notice: 'Project comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_comments/1
  # DELETE /project_comments/1.json
  def destroy
    @project_comment = ProjectComment.find(params[:id])
    @project_comment.destroy

    respond_to do |format|
      format.html { redirect_to project_comments_url }
      format.json { head :no_content }
    end
  end
end

Rails/AGB/app/helpers/project_comments_helper.rb
module ProjectCommentsHelper
end

Rails/AGB/app/views/project_comments/_form.html.erb
<%= form_for(@project_comment) do |f| %>
  <% if @project_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_comment.errors.count, "error") %> prohibited this project_comment from being saved:</h2>

      <ul>
      <% @project_comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.text_field :project_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/AGB/app/views/project_comments/edit.html.erb
<h1>Editing project_comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @project_comment %> |
<%= link_to 'Back', project_comments_path %>

Rails/AGB/app/views/project_comments/index.html.erb
<h1>Listing project_comments</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th>Title</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @project_comments.each do |project_comment| %>
  <tr>
    <td><%= project_comment.content %></td>
    <td><%= project_comment.user_id %></td>
    <td><%= project_comment.title %></td>
    <td><%= project_comment.project_id %></td>
    <td><%= link_to 'Show', project_comment %></td>
    <td><%= link_to 'Edit', edit_project_comment_path(project_comment) %></td>
    <td><%= link_to 'Destroy', project_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project comment', new_project_comment_path %>

Rails/AGB/app/views/project_comments/new.html.erb
<h1>New project_comment</h1>

<%= render 'form' %>

<%= link_to 'Back', project_comments_path %>

Rails/AGB/app/views/project_comments/show.html.erb
<p>
  <b>Content:</b>
  <%= @project_comment.content %>
</p>

<p>
  <b>User:</b>
  <%= @project_comment.user_id %>
</p>

<p>
  <b>Title:</b>
  <%= @project_comment.title %>
</p>

<p>
  <b>Project:</b>
  <%= @project_comment.project_id %>
</p>


<%= link_to 'Edit', edit_project_comment_path(@project_comment) %> |
<%= link_to 'Back', project_comments_path %>